apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd # Namespace in which ArgoCD is deployed
  annotations:
    argocd.argoproj.io/sync-wave: '-8'
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: '*'
    helm:
      values: |
        prometheusOperator:
          admissionWebhooks:
            patch:
              podAnnotations:
                sidecar.istio.io/inject: "false"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
