apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: '*'
    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodeports:
              http: 30080
              https: 30443
            hostNetwork: true
            dnsPolicy: ClusterFirstWithHostNet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
