apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  destination:
    namespace: falco
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: '*'
    helm:
      parameters:
        - name: falcosidekick.enabled
          value: 'true'
        - name: falcosidekick.webui.enabled
          value: 'true'
        - name: falcosidekick.config.talon.address
          value: 'http://falco-talon:2803'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
